config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:registrations => "user_registrations"}
  resources :users
  resources :products do
    resources :comments
  end

  resources :orders, only: [:index, :show, :create, :destroy]


  root 'static_pages#landing_page'

  get '/contact', to: 'static_pages#contact'

  get '/about', to: 'static_pages#about'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

  post 'payments/create'

  #actioncable
  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Firstapp</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  </head>

  <body>

    <% if notice %>
      <p id="notice" class="alert alert-info"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p id="alert" class="alert alert-info"><%= alert %></p>
    <% end %>


    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/static_pages/landing_page">Bike Berlin</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <%= form_tag("/products", method: "get", class: "navbar-form navbar-left", role: "search") do %>
            <div class="form-group">
              <%= label_tag(:q, "Search for:", class: "sr-only") %>
              <%= text_field_tag(:q, nil, class: "form-control", placeholder: "Search for") %>
            </div>
              <%= button_tag("Go", class: "btn btn-default btn-default-transparent") %>
              <% end %>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "home", root_path %></li>
            <li><%= link_to "products", products_path %></li>
            <li><%= link_to "about", about_path %></li>
            <li><%= link_to "contact", contact_path %></li>
            <!-- login -->
            <li>
              <% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              <% else %>
                <%= link_to('Login', new_user_session_path) %>
              <% end %>
             </li><!-- /login -->
          </ul><!-- /navbar-right -->
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <%= yield %>

    <footer class="navbar-fixed-bottom navbar navbar-default site-footer">
      <div class="footer-element">
        &copy; 2017 Bike Berlin
      </div>
    </footer>
  </body>
</html>